services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
    networks:
      - api-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - api-net
      
  api1:
    build: .
    container_name: api1
    hostname: api1
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: rinha
      DB_PASSWORD: rinha
      DB_NAME: rinha
      REDIS_ADDR: redis:6379
      DEFAULT_PROCESSOR_BASE_URL: http://payment-processor-default:8080/
      FALLBACK_PROCESSOR_BASE_URL: http://payment-processor-fallback:8080/
    ports:
      - "9001:9999"
    depends_on:
      - db
      - redis
    networks:
      - api-net

  api2:
    build: .
    container_name: api2
    hostname: api2
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: rinha
      DB_PASSWORD: rinha
      DB_NAME: rinha
      REDIS_ADDR: redis:6379
      DEFAULT_PROCESSOR_BASE_URL: http://payment-processor-default:8080/
      FALLBACK_PROCESSOR_BASE_URL: http://payment-processor-fallback:8080/
    ports:
      - "9002:9999"
    depends_on:
      - db
      - redis
    networks:
      - api-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"
    networks:
      - api-net

networks:
  api-net:
    driver: bridge